apiVersion: v1
kind: Service
metadata:
  name: sumato  # Changed from 'zomato' to 'sumato'
  labels:
    app: sumato  # Changed from 'zomato' to 'sumato'
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
  selector:
    app: sumato  # Changed from 'zomato' to 'sumato'
